/*
 * This file is generated by jOOQ.
 */
package org.go.together.repository.tables;


import org.go.together.repository.DefaultSchema;
import org.go.together.repository.Indexes;
import org.go.together.repository.Keys;
import org.go.together.repository.tables.records.SystemUserRecord;
import org.jooq.*;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;

import javax.annotation.processing.Generated;
import java.util.Arrays;
import java.util.List;


/**
 * This class is generated by jOOQ.
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.12.3"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class SystemUser extends TableImpl<SystemUserRecord> {

    /**
     * The reference instance of <code>SYSTEM_USER</code>
     */
    public static final SystemUser SYSTEM_USER = new SystemUser();
    private static final long serialVersionUID = -401900295;
    /**
     * The column <code>SYSTEM_USER.ID</code>.
     */
    public final TableField<SystemUserRecord, String> ID = createField(DSL.name("ID"), org.jooq.impl.SQLDataType.VARCHAR(255).nullable(false), this, "");
    /**
     * The column <code>SYSTEM_USER.DESCRIPTION</code>.
     */
    public final TableField<SystemUserRecord, String> DESCRIPTION = createField(DSL.name("DESCRIPTION"), org.jooq.impl.SQLDataType.VARCHAR(255), this, "");
    /**
     * The column <code>SYSTEM_USER.FIRST_NAME</code>.
     */
    public final TableField<SystemUserRecord, String> FIRST_NAME = createField(DSL.name("FIRST_NAME"), org.jooq.impl.SQLDataType.VARCHAR(255), this, "");
    /**
     * The column <code>SYSTEM_USER.LAST_NAME</code>.
     */
    public final TableField<SystemUserRecord, String> LAST_NAME = createField(DSL.name("LAST_NAME"), org.jooq.impl.SQLDataType.VARCHAR(255), this, "");
    /**
     * The column <code>SYSTEM_USER.LOCATION_ID</code>.
     */
    public final TableField<SystemUserRecord, String> LOCATION_ID = createField(DSL.name("LOCATION_ID"), org.jooq.impl.SQLDataType.VARCHAR(255), this, "");
    /**
     * The column <code>SYSTEM_USER.LOGIN</code>.
     */
    public final TableField<SystemUserRecord, String> LOGIN = createField(DSL.name("LOGIN"), org.jooq.impl.SQLDataType.VARCHAR(255), this, "");
    /**
     * The column <code>SYSTEM_USER.MAIL</code>.
     */
    public final TableField<SystemUserRecord, String> MAIL = createField(DSL.name("MAIL"), org.jooq.impl.SQLDataType.VARCHAR(255), this, "");
    /**
     * The column <code>SYSTEM_USER.PASSWORD</code>.
     */
    public final TableField<SystemUserRecord, String> PASSWORD = createField(DSL.name("PASSWORD"), org.jooq.impl.SQLDataType.VARCHAR(255), this, "");
    /**
     * The column <code>SYSTEM_USER.PHOTO_ID</code>.
     */
    public final TableField<SystemUserRecord, String> PHOTO_ID = createField(DSL.name("PHOTO_ID"), org.jooq.impl.SQLDataType.VARCHAR(255), this, "");
    /**
     * The column <code>SYSTEM_USER.ROLE</code>.
     */
    public final TableField<SystemUserRecord, String> ROLE = createField(DSL.name("ROLE"), org.jooq.impl.SQLDataType.VARCHAR(255), this, "");

    /**
     * Create a <code>SYSTEM_USER</code> table reference
     */
    public SystemUser() {
        this(DSL.name("SYSTEM_USER"), null);
    }

    /**
     * Create an aliased <code>SYSTEM_USER</code> table reference
     */
    public SystemUser(String alias) {
        this(DSL.name(alias), SYSTEM_USER);
    }

    /**
     * Create an aliased <code>SYSTEM_USER</code> table reference
     */
    public SystemUser(Name alias) {
        this(alias, SYSTEM_USER);
    }

    private SystemUser(Name alias, Table<SystemUserRecord> aliased) {
        this(alias, aliased, null);
    }

    private SystemUser(Name alias, Table<SystemUserRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> SystemUser(Table<O> child, ForeignKey<O, SystemUserRecord> key) {
        super(child, key, SYSTEM_USER);
    }

    /**
     * The class holding records for this type
     */
    @Override
    public Class<SystemUserRecord> getRecordType() {
        return SystemUserRecord.class;
    }

    @Override
    public Schema getSchema() {
        return DefaultSchema.DEFAULT_SCHEMA;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.PRIMARY_KEY_2);
    }

    @Override
    public UniqueKey<SystemUserRecord> getPrimaryKey() {
        return Keys.CONSTRAINT_2;
    }

    @Override
    public List<UniqueKey<SystemUserRecord>> getKeys() {
        return Arrays.<UniqueKey<SystemUserRecord>>asList(Keys.CONSTRAINT_2);
    }

    @Override
    public SystemUser as(String alias) {
        return new SystemUser(DSL.name(alias), this);
    }

    @Override
    public SystemUser as(Name alias) {
        return new SystemUser(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public SystemUser rename(String name) {
        return new SystemUser(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public SystemUser rename(Name name) {
        return new SystemUser(name, null);
    }

    // -------------------------------------------------------------------------
    // Row10 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row10<String, String, String, String, String, String, String, String, String, String> fieldsRow() {
        return (Row10) super.fieldsRow();
    }
}
