/*
 * This file is generated by jOOQ.
 */
package org.go.together.repository.tables;


import org.go.together.repository.DefaultSchema;
import org.go.together.repository.Indexes;
import org.go.together.repository.Keys;
import org.go.together.repository.tables.records.SystemUserLanguageRecord;
import org.jooq.*;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;

import javax.annotation.processing.Generated;
import java.util.Arrays;
import java.util.List;


/**
 * This class is generated by jOOQ.
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.12.3"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class SystemUserLanguage extends TableImpl<SystemUserLanguageRecord> {

    /**
     * The reference instance of <code>SYSTEM_USER_LANGUAGE</code>
     */
    public static final SystemUserLanguage SYSTEM_USER_LANGUAGE = new SystemUserLanguage();
    private static final long serialVersionUID = -698828747;
    /**
     * The column <code>SYSTEM_USER_LANGUAGE.USER_ID</code>.
     */
    public final TableField<SystemUserLanguageRecord, String> USER_ID = createField(DSL.name("USER_ID"), org.jooq.impl.SQLDataType.VARCHAR(255).nullable(false), this, "");
    /**
     * The column <code>SYSTEM_USER_LANGUAGE.LANGUAGE_ID</code>.
     */
    public final TableField<SystemUserLanguageRecord, String> LANGUAGE_ID = createField(DSL.name("LANGUAGE_ID"), org.jooq.impl.SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * Create a <code>SYSTEM_USER_LANGUAGE</code> table reference
     */
    public SystemUserLanguage() {
        this(DSL.name("SYSTEM_USER_LANGUAGE"), null);
    }

    /**
     * Create an aliased <code>SYSTEM_USER_LANGUAGE</code> table reference
     */
    public SystemUserLanguage(String alias) {
        this(DSL.name(alias), SYSTEM_USER_LANGUAGE);
    }

    /**
     * Create an aliased <code>SYSTEM_USER_LANGUAGE</code> table reference
     */
    public SystemUserLanguage(Name alias) {
        this(alias, SYSTEM_USER_LANGUAGE);
    }

    private SystemUserLanguage(Name alias, Table<SystemUserLanguageRecord> aliased) {
        this(alias, aliased, null);
    }

    private SystemUserLanguage(Name alias, Table<SystemUserLanguageRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> SystemUserLanguage(Table<O> child, ForeignKey<O, SystemUserLanguageRecord> key) {
        super(child, key, SYSTEM_USER_LANGUAGE);
    }

    /**
     * The class holding records for this type
     */
    @Override
    public Class<SystemUserLanguageRecord> getRecordType() {
        return SystemUserLanguageRecord.class;
    }

    @Override
    public Schema getSchema() {
        return DefaultSchema.DEFAULT_SCHEMA;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.FK2LVTM4349YMCQPY8BW1ATXHPW_INDEX_5, Indexes.FKHQKEATSFIMT3R8N7KFKQI7BBY_INDEX_5, Indexes.PRIMARY_KEY_56);
    }

    @Override
    public UniqueKey<SystemUserLanguageRecord> getPrimaryKey() {
        return Keys.CONSTRAINT_56;
    }

    @Override
    public List<UniqueKey<SystemUserLanguageRecord>> getKeys() {
        return Arrays.<UniqueKey<SystemUserLanguageRecord>>asList(Keys.CONSTRAINT_56);
    }

    @Override
    public List<ForeignKey<SystemUserLanguageRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<SystemUserLanguageRecord, ?>>asList(Keys.FK2LVTM4349YMCQPY8BW1ATXHPW, Keys.FKHQKEATSFIMT3R8N7KFKQI7BBY);
    }

    public SystemUser systemUser() {
        return new SystemUser(this, Keys.FK2LVTM4349YMCQPY8BW1ATXHPW);
    }

    public Language language() {
        return new Language(this, Keys.FKHQKEATSFIMT3R8N7KFKQI7BBY);
    }

    @Override
    public SystemUserLanguage as(String alias) {
        return new SystemUserLanguage(DSL.name(alias), this);
    }

    @Override
    public SystemUserLanguage as(Name alias) {
        return new SystemUserLanguage(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public SystemUserLanguage rename(String name) {
        return new SystemUserLanguage(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public SystemUserLanguage rename(Name name) {
        return new SystemUserLanguage(name, null);
    }

    // -------------------------------------------------------------------------
    // Row2 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row2<String, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }
}
