/*
 * This file is generated by jOOQ.
 */
package org.go.together.repository.tables;


import org.go.together.repository.DefaultSchema;
import org.go.together.repository.Indexes;
import org.go.together.repository.Keys;
import org.go.together.repository.tables.records.SystemUserInterestRecord;
import org.jooq.*;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;

import javax.annotation.processing.Generated;
import java.util.Arrays;
import java.util.List;


/**
 * This class is generated by jOOQ.
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.12.3"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class SystemUserInterest extends TableImpl<SystemUserInterestRecord> {

    /**
     * The reference instance of <code>SYSTEM_USER_INTEREST</code>
     */
    public static final SystemUserInterest SYSTEM_USER_INTEREST = new SystemUserInterest();
    private static final long serialVersionUID = -785900309;
    /**
     * The column <code>SYSTEM_USER_INTEREST.USER_ID</code>.
     */
    public final TableField<SystemUserInterestRecord, String> USER_ID = createField(DSL.name("USER_ID"), org.jooq.impl.SQLDataType.VARCHAR(255).nullable(false), this, "");
    /**
     * The column <code>SYSTEM_USER_INTEREST.INTEREST_ID</code>.
     */
    public final TableField<SystemUserInterestRecord, String> INTEREST_ID = createField(DSL.name("INTEREST_ID"), org.jooq.impl.SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * Create a <code>SYSTEM_USER_INTEREST</code> table reference
     */
    public SystemUserInterest() {
        this(DSL.name("SYSTEM_USER_INTEREST"), null);
    }

    /**
     * Create an aliased <code>SYSTEM_USER_INTEREST</code> table reference
     */
    public SystemUserInterest(String alias) {
        this(DSL.name(alias), SYSTEM_USER_INTEREST);
    }

    /**
     * Create an aliased <code>SYSTEM_USER_INTEREST</code> table reference
     */
    public SystemUserInterest(Name alias) {
        this(alias, SYSTEM_USER_INTEREST);
    }

    private SystemUserInterest(Name alias, Table<SystemUserInterestRecord> aliased) {
        this(alias, aliased, null);
    }

    private SystemUserInterest(Name alias, Table<SystemUserInterestRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> SystemUserInterest(Table<O> child, ForeignKey<O, SystemUserInterestRecord> key) {
        super(child, key, SYSTEM_USER_INTEREST);
    }

    /**
     * The class holding records for this type
     */
    @Override
    public Class<SystemUserInterestRecord> getRecordType() {
        return SystemUserInterestRecord.class;
    }

    @Override
    public Schema getSchema() {
        return DefaultSchema.DEFAULT_SCHEMA;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.FKFK5SWC6M71I98F34WJ5XJ02W3_INDEX_D, Indexes.FKJOKHBS177RB5WFALVJFOEDMUP_INDEX_D, Indexes.PRIMARY_KEY_D);
    }

    @Override
    public UniqueKey<SystemUserInterestRecord> getPrimaryKey() {
        return Keys.CONSTRAINT_D;
    }

    @Override
    public List<UniqueKey<SystemUserInterestRecord>> getKeys() {
        return Arrays.<UniqueKey<SystemUserInterestRecord>>asList(Keys.CONSTRAINT_D);
    }

    @Override
    public List<ForeignKey<SystemUserInterestRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<SystemUserInterestRecord, ?>>asList(Keys.FKFK5SWC6M71I98F34WJ5XJ02W3, Keys.FKJOKHBS177RB5WFALVJFOEDMUP);
    }

    public SystemUser systemUser() {
        return new SystemUser(this, Keys.FKFK5SWC6M71I98F34WJ5XJ02W3);
    }

    public Interest interest() {
        return new Interest(this, Keys.FKJOKHBS177RB5WFALVJFOEDMUP);
    }

    @Override
    public SystemUserInterest as(String alias) {
        return new SystemUserInterest(DSL.name(alias), this);
    }

    @Override
    public SystemUserInterest as(Name alias) {
        return new SystemUserInterest(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public SystemUserInterest rename(String name) {
        return new SystemUserInterest(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public SystemUserInterest rename(Name name) {
        return new SystemUserInterest(name, null);
    }

    // -------------------------------------------------------------------------
    // Row2 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row2<String, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }
}
