/*
 * This file is generated by jOOQ.
 */
package org.go.together.repository.tables.records;


import org.go.together.repository.tables.AppuserLanguage;
import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;

import javax.annotation.processing.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.12.3"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class AppuserLanguageRecord extends UpdatableRecordImpl<AppuserLanguageRecord> implements Record2<String, String> {

    private static final long serialVersionUID = -1162044858;

    /**
     * Create a detached AppuserLanguageRecord
     */
    public AppuserLanguageRecord() {
        super(AppuserLanguage.APPUSER_LANGUAGE);
    }

    /**
     * Create a detached, initialised AppuserLanguageRecord
     */
    public AppuserLanguageRecord(String appuserId, String languagesId) {
        super(AppuserLanguage.APPUSER_LANGUAGE);

        set(0, appuserId);
        set(1, languagesId);
    }

    /**
     * Getter for <code>APPUSER_LANGUAGE.APPUSER_ID</code>.
     */
    public String getAppuserId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>APPUSER_LANGUAGE.APPUSER_ID</code>.
     */
    public void setAppuserId(String value) {
        set(0, value);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * Getter for <code>APPUSER_LANGUAGE.LANGUAGES_ID</code>.
     */
    public String getLanguagesId() {
        return (String) get(1);
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    /**
     * Setter for <code>APPUSER_LANGUAGE.LANGUAGES_ID</code>.
     */
    public void setLanguagesId(String value) {
        set(1, value);
    }

    @Override
    public Record2<String, String> key() {
        return (Record2) super.key();
    }

    @Override
    public Row2<String, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    @Override
    public Row2<String, String> valuesRow() {
        return (Row2) super.valuesRow();
    }

    @Override
    public Field<String> field1() {
        return AppuserLanguage.APPUSER_LANGUAGE.APPUSER_ID;
    }

    @Override
    public Field<String> field2() {
        return AppuserLanguage.APPUSER_LANGUAGE.LANGUAGES_ID;
    }

    @Override
    public String component1() {
        return getAppuserId();
    }

    @Override
    public String component2() {
        return getLanguagesId();
    }

    @Override
    public String value1() {
        return getAppuserId();
    }

    @Override
    public String value2() {
        return getLanguagesId();
    }

    @Override
    public AppuserLanguageRecord value1(String value) {
        setAppuserId(value);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    @Override
    public AppuserLanguageRecord value2(String value) {
        setLanguagesId(value);
        return this;
    }

    @Override
    public AppuserLanguageRecord values(String value1, String value2) {
        value1(value1);
        value2(value2);
        return this;
    }
}
