/*
 * This file is generated by jOOQ.
 */
package org.go.together.repository.tables.records;


import org.go.together.repository.tables.Appuser;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record10;
import org.jooq.Row10;
import org.jooq.impl.UpdatableRecordImpl;

import javax.annotation.processing.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.12.3"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class AppuserRecord extends UpdatableRecordImpl<AppuserRecord> implements Record10<String, String, String, String, String, String, String, String, String, String> {

    private static final long serialVersionUID = -296316247;

    /**
     * Create a detached AppuserRecord
     */
    public AppuserRecord() {
        super(Appuser.APPUSER);
    }

    /**
     * Create a detached, initialised AppuserRecord
     */
    public AppuserRecord(String id, String description, String firstname, String lastname, String locationid, String login, String mail, String password, String photoid, String role) {
        super(Appuser.APPUSER);

        set(0, id);
        set(1, description);
        set(2, firstname);
        set(3, lastname);
        set(4, locationid);
        set(5, login);
        set(6, mail);
        set(7, password);
        set(8, photoid);
        set(9, role);
    }

    /**
     * Getter for <code>APPUSER.ID</code>.
     */
    public String getId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>APPUSER.ID</code>.
     */
    public void setId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>APPUSER.DESCRIPTION</code>.
     */
    public String getDescription() {
        return (String) get(1);
    }

    /**
     * Setter for <code>APPUSER.DESCRIPTION</code>.
     */
    public void setDescription(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>APPUSER.FIRSTNAME</code>.
     */
    public String getFirstname() {
        return (String) get(2);
    }

    /**
     * Setter for <code>APPUSER.FIRSTNAME</code>.
     */
    public void setFirstname(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>APPUSER.LASTNAME</code>.
     */
    public String getLastname() {
        return (String) get(3);
    }

    /**
     * Setter for <code>APPUSER.LASTNAME</code>.
     */
    public void setLastname(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>APPUSER.LOCATIONID</code>.
     */
    public String getLocationid() {
        return (String) get(4);
    }

    /**
     * Setter for <code>APPUSER.LOCATIONID</code>.
     */
    public void setLocationid(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>APPUSER.LOGIN</code>.
     */
    public String getLogin() {
        return (String) get(5);
    }

    /**
     * Setter for <code>APPUSER.LOGIN</code>.
     */
    public void setLogin(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>APPUSER.MAIL</code>.
     */
    public String getMail() {
        return (String) get(6);
    }

    /**
     * Setter for <code>APPUSER.MAIL</code>.
     */
    public void setMail(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>APPUSER.PASSWORD</code>.
     */
    public String getPassword() {
        return (String) get(7);
    }

    /**
     * Setter for <code>APPUSER.PASSWORD</code>.
     */
    public void setPassword(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>APPUSER.PHOTOID</code>.
     */
    public String getPhotoid() {
        return (String) get(8);
    }

    /**
     * Setter for <code>APPUSER.PHOTOID</code>.
     */
    public void setPhotoid(String value) {
        set(8, value);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * Getter for <code>APPUSER.ROLE</code>.
     */
    public String getRole() {
        return (String) get(9);
    }

    // -------------------------------------------------------------------------
    // Record10 type implementation
    // -------------------------------------------------------------------------

    /**
     * Setter for <code>APPUSER.ROLE</code>.
     */
    public void setRole(String value) {
        set(9, value);
    }

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    @Override
    public Row10<String, String, String, String, String, String, String, String, String, String> fieldsRow() {
        return (Row10) super.fieldsRow();
    }

    @Override
    public Row10<String, String, String, String, String, String, String, String, String, String> valuesRow() {
        return (Row10) super.valuesRow();
    }

    @Override
    public Field<String> field1() {
        return Appuser.APPUSER.ID;
    }

    @Override
    public Field<String> field2() {
        return Appuser.APPUSER.DESCRIPTION;
    }

    @Override
    public Field<String> field3() {
        return Appuser.APPUSER.FIRSTNAME;
    }

    @Override
    public Field<String> field4() {
        return Appuser.APPUSER.LASTNAME;
    }

    @Override
    public Field<String> field5() {
        return Appuser.APPUSER.LOCATIONID;
    }

    @Override
    public Field<String> field6() {
        return Appuser.APPUSER.LOGIN;
    }

    @Override
    public Field<String> field7() {
        return Appuser.APPUSER.MAIL;
    }

    @Override
    public Field<String> field8() {
        return Appuser.APPUSER.PASSWORD;
    }

    @Override
    public Field<String> field9() {
        return Appuser.APPUSER.PHOTOID;
    }

    @Override
    public Field<String> field10() {
        return Appuser.APPUSER.ROLE;
    }

    @Override
    public String component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getDescription();
    }

    @Override
    public String component3() {
        return getFirstname();
    }

    @Override
    public String component4() {
        return getLastname();
    }

    @Override
    public String component5() {
        return getLocationid();
    }

    @Override
    public String component6() {
        return getLogin();
    }

    @Override
    public String component7() {
        return getMail();
    }

    @Override
    public String component8() {
        return getPassword();
    }

    @Override
    public String component9() {
        return getPhotoid();
    }

    @Override
    public String component10() {
        return getRole();
    }

    @Override
    public String value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getDescription();
    }

    @Override
    public String value3() {
        return getFirstname();
    }

    @Override
    public String value4() {
        return getLastname();
    }

    @Override
    public String value5() {
        return getLocationid();
    }

    @Override
    public String value6() {
        return getLogin();
    }

    @Override
    public String value7() {
        return getMail();
    }

    @Override
    public String value8() {
        return getPassword();
    }

    @Override
    public String value9() {
        return getPhotoid();
    }

    @Override
    public String value10() {
        return getRole();
    }

    @Override
    public AppuserRecord value1(String value) {
        setId(value);
        return this;
    }

    @Override
    public AppuserRecord value2(String value) {
        setDescription(value);
        return this;
    }

    @Override
    public AppuserRecord value3(String value) {
        setFirstname(value);
        return this;
    }

    @Override
    public AppuserRecord value4(String value) {
        setLastname(value);
        return this;
    }

    @Override
    public AppuserRecord value5(String value) {
        setLocationid(value);
        return this;
    }

    @Override
    public AppuserRecord value6(String value) {
        setLogin(value);
        return this;
    }

    @Override
    public AppuserRecord value7(String value) {
        setMail(value);
        return this;
    }

    @Override
    public AppuserRecord value8(String value) {
        setPassword(value);
        return this;
    }

    @Override
    public AppuserRecord value9(String value) {
        setPhotoid(value);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    @Override
    public AppuserRecord value10(String value) {
        setRole(value);
        return this;
    }

    @Override
    public AppuserRecord values(String value1, String value2, String value3, String value4, String value5, String value6, String value7, String value8, String value9, String value10) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        return this;
    }
}
