/*
 * This file is generated by jOOQ.
 */
package org.go.together.repository.tables.records;


import org.go.together.repository.tables.Interest;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;

import javax.annotation.processing.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.12.3"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class InterestRecord extends UpdatableRecordImpl<InterestRecord> implements Record2<String, String> {

    private static final long serialVersionUID = -515020138;

    /**
     * Create a detached InterestRecord
     */
    public InterestRecord() {
        super(Interest.INTEREST);
    }

    /**
     * Create a detached, initialised InterestRecord
     */
    public InterestRecord(String id, String name) {
        super(Interest.INTEREST);

        set(0, id);
        set(1, name);
    }

    /**
     * Getter for <code>INTEREST.ID</code>.
     */
    public String getId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>INTEREST.ID</code>.
     */
    public void setId(String value) {
        set(0, value);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * Getter for <code>INTEREST.NAME</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    /**
     * Setter for <code>INTEREST.NAME</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    @Override
    public Row2<String, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    @Override
    public Row2<String, String> valuesRow() {
        return (Row2) super.valuesRow();
    }

    @Override
    public Field<String> field1() {
        return Interest.INTEREST.ID;
    }

    @Override
    public Field<String> field2() {
        return Interest.INTEREST.NAME;
    }

    @Override
    public String component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getName();
    }

    @Override
    public String value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getName();
    }

    @Override
    public InterestRecord value1(String value) {
        setId(value);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    @Override
    public InterestRecord value2(String value) {
        setName(value);
        return this;
    }

    @Override
    public InterestRecord values(String value1, String value2) {
        value1(value1);
        value2(value2);
        return this;
    }
}
