/*
 * This file is generated by jOOQ.
 */
package org.go.together.repository.tables.records;


import org.go.together.repository.tables.SystemUser;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record10;
import org.jooq.Row10;
import org.jooq.impl.UpdatableRecordImpl;

import javax.annotation.processing.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.12.3"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class SystemUserRecord extends UpdatableRecordImpl<SystemUserRecord> implements Record10<String, String, String, String, String, String, String, String, String, String> {

    private static final long serialVersionUID = -795837627;

    /**
     * Create a detached SystemUserRecord
     */
    public SystemUserRecord() {
        super(SystemUser.SYSTEM_USER);
    }

    /**
     * Create a detached, initialised SystemUserRecord
     */
    public SystemUserRecord(String id, String description, String firstName, String lastName, String locationId, String login, String mail, String password, String photoId, String role) {
        super(SystemUser.SYSTEM_USER);

        set(0, id);
        set(1, description);
        set(2, firstName);
        set(3, lastName);
        set(4, locationId);
        set(5, login);
        set(6, mail);
        set(7, password);
        set(8, photoId);
        set(9, role);
    }

    /**
     * Getter for <code>SYSTEM_USER.ID</code>.
     */
    public String getId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>SYSTEM_USER.ID</code>.
     */
    public void setId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>SYSTEM_USER.DESCRIPTION</code>.
     */
    public String getDescription() {
        return (String) get(1);
    }

    /**
     * Setter for <code>SYSTEM_USER.DESCRIPTION</code>.
     */
    public void setDescription(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>SYSTEM_USER.FIRST_NAME</code>.
     */
    public String getFirstName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>SYSTEM_USER.FIRST_NAME</code>.
     */
    public void setFirstName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>SYSTEM_USER.LAST_NAME</code>.
     */
    public String getLastName() {
        return (String) get(3);
    }

    /**
     * Setter for <code>SYSTEM_USER.LAST_NAME</code>.
     */
    public void setLastName(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>SYSTEM_USER.LOCATION_ID</code>.
     */
    public String getLocationId() {
        return (String) get(4);
    }

    /**
     * Setter for <code>SYSTEM_USER.LOCATION_ID</code>.
     */
    public void setLocationId(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>SYSTEM_USER.LOGIN</code>.
     */
    public String getLogin() {
        return (String) get(5);
    }

    /**
     * Setter for <code>SYSTEM_USER.LOGIN</code>.
     */
    public void setLogin(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>SYSTEM_USER.MAIL</code>.
     */
    public String getMail() {
        return (String) get(6);
    }

    /**
     * Setter for <code>SYSTEM_USER.MAIL</code>.
     */
    public void setMail(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>SYSTEM_USER.PASSWORD</code>.
     */
    public String getPassword() {
        return (String) get(7);
    }

    /**
     * Setter for <code>SYSTEM_USER.PASSWORD</code>.
     */
    public void setPassword(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>SYSTEM_USER.PHOTO_ID</code>.
     */
    public String getPhotoId() {
        return (String) get(8);
    }

    /**
     * Setter for <code>SYSTEM_USER.PHOTO_ID</code>.
     */
    public void setPhotoId(String value) {
        set(8, value);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record10 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row10<String, String, String, String, String, String, String, String, String, String> fieldsRow() {
        return (Row10) super.fieldsRow();
    }

    @Override
    public Row10<String, String, String, String, String, String, String, String, String, String> valuesRow() {
        return (Row10) super.valuesRow();
    }

    /**
     * Getter for <code>SYSTEM_USER.ROLE</code>.
     */
    public String getRole() {
        return (String) get(9);
    }

    /**
     * Setter for <code>SYSTEM_USER.ROLE</code>.
     */
    public void setRole(String value) {
        set(9, value);
    }

    @Override
    public Field<String> field1() {
        return SystemUser.SYSTEM_USER.ID;
    }

    @Override
    public Field<String> field2() {
        return SystemUser.SYSTEM_USER.DESCRIPTION;
    }

    @Override
    public Field<String> field3() {
        return SystemUser.SYSTEM_USER.FIRST_NAME;
    }

    @Override
    public Field<String> field4() {
        return SystemUser.SYSTEM_USER.LAST_NAME;
    }

    @Override
    public Field<String> field5() {
        return SystemUser.SYSTEM_USER.LOCATION_ID;
    }

    @Override
    public Field<String> field6() {
        return SystemUser.SYSTEM_USER.LOGIN;
    }

    @Override
    public Field<String> field7() {
        return SystemUser.SYSTEM_USER.MAIL;
    }

    @Override
    public Field<String> field8() {
        return SystemUser.SYSTEM_USER.PASSWORD;
    }

    @Override
    public String component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getDescription();
    }

    @Override
    public Field<String> field9() {
        return SystemUser.SYSTEM_USER.PHOTO_ID;
    }

    @Override
    public Field<String> field10() {
        return SystemUser.SYSTEM_USER.ROLE;
    }

    @Override
    public String component3() {
        return getFirstName();
    }

    @Override
    public String component6() {
        return getLogin();
    }

    @Override
    public String component7() {
        return getMail();
    }

    @Override
    public String component8() {
        return getPassword();
    }

    @Override
    public String component4() {
        return getLastName();
    }

    @Override
    public String component10() {
        return getRole();
    }

    @Override
    public String value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getDescription();
    }

    @Override
    public String component5() {
        return getLocationId();
    }

    @Override
    public String component9() {
        return getPhotoId();
    }

    @Override
    public String value3() {
        return getFirstName();
    }

    @Override
    public String value6() {
        return getLogin();
    }

    @Override
    public String value7() {
        return getMail();
    }

    @Override
    public String value8() {
        return getPassword();
    }

    @Override
    public String value4() {
        return getLastName();
    }

    @Override
    public String value10() {
        return getRole();
    }

    @Override
    public String value5() {
        return getLocationId();
    }

    @Override
    public String value9() {
        return getPhotoId();
    }

    @Override
    public SystemUserRecord value1(String value) {
        setId(value);
        return this;
    }

    @Override
    public SystemUserRecord value2(String value) {
        setDescription(value);
        return this;
    }

    @Override
    public SystemUserRecord value3(String value) {
        setFirstName(value);
        return this;
    }

    @Override
    public SystemUserRecord value4(String value) {
        setLastName(value);
        return this;
    }

    @Override
    public SystemUserRecord value5(String value) {
        setLocationId(value);
        return this;
    }

    @Override
    public SystemUserRecord value6(String value) {
        setLogin(value);
        return this;
    }

    @Override
    public SystemUserRecord value7(String value) {
        setMail(value);
        return this;
    }

    @Override
    public SystemUserRecord value8(String value) {
        setPassword(value);
        return this;
    }

    @Override
    public SystemUserRecord value9(String value) {
        setPhotoId(value);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    @Override
    public SystemUserRecord value10(String value) {
        setRole(value);
        return this;
    }

    @Override
    public SystemUserRecord values(String value1, String value2, String value3, String value4, String value5, String value6, String value7, String value8, String value9, String value10) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        return this;
    }
}
