/*
 * This file is generated by jOOQ.
 */
package org.go.together.repository.tables.records;


import org.go.together.repository.tables.SystemUserInterest;
import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;

import javax.annotation.processing.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.12.3"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class SystemUserInterestRecord extends UpdatableRecordImpl<SystemUserInterestRecord> implements Record2<String, String> {

    private static final long serialVersionUID = 2104272016;

    /**
     * Create a detached SystemUserInterestRecord
     */
    public SystemUserInterestRecord() {
        super(SystemUserInterest.SYSTEM_USER_INTEREST);
    }

    /**
     * Create a detached, initialised SystemUserInterestRecord
     */
    public SystemUserInterestRecord(String userId, String interestId) {
        super(SystemUserInterest.SYSTEM_USER_INTEREST);

        set(0, userId);
        set(1, interestId);
    }

    /**
     * Getter for <code>SYSTEM_USER_INTEREST.USER_ID</code>.
     */
    public String getUserId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>SYSTEM_USER_INTEREST.USER_ID</code>.
     */
    public void setUserId(String value) {
        set(0, value);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record2<String, String> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row2<String, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    @Override
    public Row2<String, String> valuesRow() {
        return (Row2) super.valuesRow();
    }

    /**
     * Getter for <code>SYSTEM_USER_INTEREST.INTEREST_ID</code>.
     */
    public String getInterestId() {
        return (String) get(1);
    }

    /**
     * Setter for <code>SYSTEM_USER_INTEREST.INTEREST_ID</code>.
     */
    public void setInterestId(String value) {
        set(1, value);
    }

    @Override
    public Field<String> field1() {
        return SystemUserInterest.SYSTEM_USER_INTEREST.USER_ID;
    }

    @Override
    public Field<String> field2() {
        return SystemUserInterest.SYSTEM_USER_INTEREST.INTEREST_ID;
    }

    @Override
    public String component1() {
        return getUserId();
    }

    @Override
    public String component2() {
        return getInterestId();
    }

    @Override
    public String value1() {
        return getUserId();
    }

    @Override
    public String value2() {
        return getInterestId();
    }

    @Override
    public SystemUserInterestRecord value1(String value) {
        setUserId(value);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    @Override
    public SystemUserInterestRecord value2(String value) {
        setInterestId(value);
        return this;
    }

    @Override
    public SystemUserInterestRecord values(String value1, String value2) {
        value1(value1);
        value2(value2);
        return this;
    }
}
