export const EMPTY_MAIL = '* Enter mail';
export const EMPTY_LOGIN = '* Enter login';
export const EMPTY_FIRST_NAME = '* Enter first name';
export const EMPTY_LAST_NAME = '* Enter last name';
export const EMPTY_PASSWORD = '* Enter password';
export const GOOD_MAIL = '';
export const GOOD_LOGIN = '';
export const GOOD_FIRST_NAME = '';
export const GOOD_LAST_NAME = '';
export const GOOD_PASSWORD = '';
export const GOOD_CONFIRM_PASSWORD = '';
export const GOOD_DESCRIPTION = '';
export const GOOD_PHOTO = '';
export const NOT_GOOD_MAIL = '* Mail is busy';
export const NOT_GOOD_LOGIN = '* Login is busy';
export const NOT_GOOD_FIRST_NAME = '* First name cannot contain numbers';
export const NOT_GOOD_LAST_NAME = '* Last name cannot contain numbers';
export const NOT_GOOD_CONFIRM_PASSWORD = '* Passwords do not match';
export const NOT_GOOD_PASSWORD = '*  Password should be 8 or more symbols';
export const NOT_GOOD_DESCRIPTION = "*  Description shouldn't be more than 255 symbols";
export const NOT_GOOD_PHOTO_URL = "* You enter wrong photo url";
export const NOT_GOOD_PHOTO_FILE_EXT = "* You choose file with wrong extension (not png/jpg/jpeg)";
export const NOT_GOOD_PHOTO_FILE_WITH_WRONG_SIZE = "* You choose file with wrong size (max 5 Mb)";
export const PATTERN_TO_CHECK_FILE_EXTENSION = "image/(png|jpg|jpeg)";
export const PATTERN_TO_CHECK_MAIL = '(?:[a-z0-9!#$%&\'*+/=?^_`{|}~-]+(?:\\.[a-z0-9!#$%&\'*+/=?^_`{|}~-]+)*|"(?:[\x01-\x08\x0b\x0c\x0e-\x1f\x21\x23-\x5b\x5d-\x7f]|\\\\[\x01-\x09\x0b\x0c\x0e-\x7f])*")@(?:(?:[a-z0-9](?:[a-z0-9-]*[a-z0-9])?\\.)+[a-z0-9](?:[a-z0-9-]*[a-z0-9])?|\\[(?:(?:(2(5[0-5]|[0-4][0-9])|1[0-9][0-9]|[1-9]?[0-9]))\\.){3}(?:(2(5[0-5]|[0-4][0-9])|1[0-9][0-9]|[1-9]?[0-9])|[a-z0-9-]*[a-z0-9]:(?:[\x01-\x08\x0b\x0c\x0e-\x1f\x21-\x5a\x53-\x7f]|\\\\[\x01-\x09\x0b\x0c\x0e-\x7f])+)\\])';
export const PATTERN_TO_CHECK_URL = "\\b(https?|ftp|file)://[-a-zA-Z0-9+&@#/%?=~_|!:,.;]*[-a-zA-Z0-9+&@#/%=~_|]";
export const PATTERN_TO_CHECK_NAME = '^[A-Za-z]*$';

export const REGISTER_ALL_LANGUAGES = 'REGISTER_ALL_LANGUAGES';
export const REGISTER_ALL_INTERESTS = 'REGISTER_ALL_INTERESTS';
export const REGISTER_CHECK_MAIL = 'REGISTER_CHECK_MAIL';
export const REGISTER_CHECK_USERNAME = 'REGISTER_CHECK_USERNAME';
export const CREATED_USER = 'CREATED_USER';

export const FORM_ID = 'Register';