export const PERSONAL_AREA_USER_INFO = 'PERSONAL_AREA_USER_INFO';
export const PERSONAL_AREA_UPDATED_USER = 'PERSONAL_AREA_UPDATED_USER';
export const PERSONAL_AREA_CHECK_MAIL = 'PERSONAL_AREA_CHECK_MAIL';