export const PERSONAL_AREA_USER_INFO = 'PERSONAL_AREA_USER_INFO';
export const PERSONAL_AREA_UPDATED_USER = 'PERSONAL_AREA_UPDATED_USER';
export const PERSONAL_AREA_ALL_LANGUAGES = 'PERSONAL_AREA_ALL_LANGUAGES';
export const PERSONAL_AREA_ALL_INTERESTS = 'PERSONAL_AREA_ALL_INTERESTS';

export const FORM_ID = 'PersonalArea';