/*
 * This file is generated by jOOQ.
 */
package org.go.together.repository;


import org.go.together.repository.tables.*;
import org.jooq.Catalog;
import org.jooq.Sequence;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;

import javax.annotation.processing.Generated;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;


/**
 * This class is generated by jOOQ.
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.12.3"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class DefaultSchema extends SchemaImpl {

    private static final long serialVersionUID = -1352819545;

    /**
     * The reference instance of <code></code>
     */
    public static final DefaultSchema DEFAULT_SCHEMA = new DefaultSchema();

    /**
     * The table <code>INTEREST</code>.
     */
    public final Interest INTEREST = org.go.together.repository.tables.Interest.INTEREST;

    /**
     * The table <code>LANGUAGE</code>.
     */
    public final Language LANGUAGE = org.go.together.repository.tables.Language.LANGUAGE;

    /**
     * The table <code>SYSTEM_USER</code>.
     */
    public final SystemUser SYSTEM_USER = org.go.together.repository.tables.SystemUser.SYSTEM_USER;

    /**
     * The table <code>SYSTEM_USER_INTEREST</code>.
     */
    public final SystemUserInterest SYSTEM_USER_INTEREST = org.go.together.repository.tables.SystemUserInterest.SYSTEM_USER_INTEREST;

    /**
     * The table <code>SYSTEM_USER_LANGUAGE</code>.
     */
    public final SystemUserLanguage SYSTEM_USER_LANGUAGE = org.go.together.repository.tables.SystemUserLanguage.SYSTEM_USER_LANGUAGE;

    /**
     * No further instances allowed
     */
    private DefaultSchema() {
        super("", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Sequence<?>> getSequences() {
        List result = new ArrayList();
        result.addAll(getSequences0());
        return result;
    }

    private final List<Sequence<?>> getSequences0() {
        return Arrays.<Sequence<?>>asList(
                Sequences.HIBERNATE_SEQUENCE);
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
                Interest.INTEREST,
                Language.LANGUAGE,
                SystemUser.SYSTEM_USER,
                SystemUserInterest.SYSTEM_USER_INTEREST,
                SystemUserLanguage.SYSTEM_USER_LANGUAGE);
    }
}
