/*
 * This file is generated by jOOQ.
 */
package org.go.together.repository;


import org.go.together.repository.tables.*;
import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.Internal;

import javax.annotation.processing.Generated;


/**
 * A class modelling indexes of tables of the <code></code> schema.
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.12.3"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index PRIMARY_KEY_5 = Indexes0.PRIMARY_KEY_5;
    public static final Index PRIMARY_KEY_C = Indexes0.PRIMARY_KEY_C;
    public static final Index PRIMARY_KEY_2 = Indexes0.PRIMARY_KEY_2;
    public static final Index FKFK5SWC6M71I98F34WJ5XJ02W3_INDEX_D = Indexes0.FKFK5SWC6M71I98F34WJ5XJ02W3_INDEX_D;
    public static final Index FKJOKHBS177RB5WFALVJFOEDMUP_INDEX_D = Indexes0.FKJOKHBS177RB5WFALVJFOEDMUP_INDEX_D;
    public static final Index PRIMARY_KEY_D = Indexes0.PRIMARY_KEY_D;
    public static final Index FK2LVTM4349YMCQPY8BW1ATXHPW_INDEX_5 = Indexes0.FK2LVTM4349YMCQPY8BW1ATXHPW_INDEX_5;
    public static final Index FKHQKEATSFIMT3R8N7KFKQI7BBY_INDEX_5 = Indexes0.FKHQKEATSFIMT3R8N7KFKQI7BBY_INDEX_5;
    public static final Index PRIMARY_KEY_56 = Indexes0.PRIMARY_KEY_56;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 {
        public static Index PRIMARY_KEY_5 = Internal.createIndex("PRIMARY_KEY_5", Interest.INTEREST, new OrderField[]{Interest.INTEREST.ID}, true);
        public static Index PRIMARY_KEY_C = Internal.createIndex("PRIMARY_KEY_C", Language.LANGUAGE, new OrderField[]{Language.LANGUAGE.ID}, true);
        public static Index PRIMARY_KEY_2 = Internal.createIndex("PRIMARY_KEY_2", SystemUser.SYSTEM_USER, new OrderField[]{SystemUser.SYSTEM_USER.ID}, true);
        public static Index FKFK5SWC6M71I98F34WJ5XJ02W3_INDEX_D = Internal.createIndex("FKFK5SWC6M71I98F34WJ5XJ02W3_INDEX_D", SystemUserInterest.SYSTEM_USER_INTEREST, new OrderField[]{SystemUserInterest.SYSTEM_USER_INTEREST.USER_ID}, false);
        public static Index FKJOKHBS177RB5WFALVJFOEDMUP_INDEX_D = Internal.createIndex("FKJOKHBS177RB5WFALVJFOEDMUP_INDEX_D", SystemUserInterest.SYSTEM_USER_INTEREST, new OrderField[]{SystemUserInterest.SYSTEM_USER_INTEREST.INTEREST_ID}, false);
        public static Index PRIMARY_KEY_D = Internal.createIndex("PRIMARY_KEY_D", SystemUserInterest.SYSTEM_USER_INTEREST, new OrderField[]{SystemUserInterest.SYSTEM_USER_INTEREST.USER_ID, SystemUserInterest.SYSTEM_USER_INTEREST.INTEREST_ID}, true);
        public static Index FK2LVTM4349YMCQPY8BW1ATXHPW_INDEX_5 = Internal.createIndex("FK2LVTM4349YMCQPY8BW1ATXHPW_INDEX_5", SystemUserLanguage.SYSTEM_USER_LANGUAGE, new OrderField[]{SystemUserLanguage.SYSTEM_USER_LANGUAGE.USER_ID}, false);
        public static Index FKHQKEATSFIMT3R8N7KFKQI7BBY_INDEX_5 = Internal.createIndex("FKHQKEATSFIMT3R8N7KFKQI7BBY_INDEX_5", SystemUserLanguage.SYSTEM_USER_LANGUAGE, new OrderField[]{SystemUserLanguage.SYSTEM_USER_LANGUAGE.LANGUAGE_ID}, false);
        public static Index PRIMARY_KEY_56 = Internal.createIndex("PRIMARY_KEY_56", SystemUserLanguage.SYSTEM_USER_LANGUAGE, new OrderField[]{SystemUserLanguage.SYSTEM_USER_LANGUAGE.USER_ID, SystemUserLanguage.SYSTEM_USER_LANGUAGE.LANGUAGE_ID}, true);
    }
}
