/*
 * This file is generated by jOOQ.
 */
package org.go.together.repository;


import org.go.together.repository.tables.*;

import javax.annotation.processing.Generated;


/**
 * Convenience access to all tables in
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.12.3"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class Tables {

    /**
     * The table <code>INTEREST</code>.
     */
    public static final Interest INTEREST = Interest.INTEREST;

    /**
     * The table <code>LANGUAGE</code>.
     */
    public static final Language LANGUAGE = Language.LANGUAGE;

    /**
     * The table <code>SYSTEM_USER</code>.
     */
    public static final SystemUser SYSTEM_USER = SystemUser.SYSTEM_USER;

    /**
     * The table <code>SYSTEM_USER_INTEREST</code>.
     */
    public static final SystemUserInterest SYSTEM_USER_INTEREST = SystemUserInterest.SYSTEM_USER_INTEREST;

    /**
     * The table <code>SYSTEM_USER_LANGUAGE</code>.
     */
    public static final SystemUserLanguage SYSTEM_USER_LANGUAGE = SystemUserLanguage.SYSTEM_USER_LANGUAGE;
}
