/*
 * This file is generated by jOOQ.
 */
package org.go.together.repository;


import org.go.together.repository.tables.*;

import javax.annotation.processing.Generated;


/**
 * Convenience access to all tables in
 */
@Generated(
        value = {
                "http://www.jooq.org",
                "jOOQ version:3.12.3"
        },
        comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class Tables {

    /**
     * The table <code>APPUSER</code>.
     */
    public static final Appuser APPUSER = Appuser.APPUSER;

    /**
     * The table <code>APPUSER_INTEREST</code>.
     */
    public static final AppuserInterest APPUSER_INTEREST = AppuserInterest.APPUSER_INTEREST;

    /**
     * The table <code>APPUSER_LANGUAGE</code>.
     */
    public static final AppuserLanguage APPUSER_LANGUAGE = AppuserLanguage.APPUSER_LANGUAGE;

    /**
     * The table <code>INTEREST</code>.
     */
    public static final Interest INTEREST = Interest.INTEREST;

    /**
     * The table <code>LANGUAGE</code>.
     */
    public static final Language LANGUAGE = Language.LANGUAGE;
}
