server:
  port: 8088
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka
kafka:
  groupId: auth-service
  server: localhost:9092
  replyPostfix: _reply
  readReplyPrefix: _read_
  createReplyPrefix: _create_
  updateReplyPrefix: _update_
  deleteReplyPrefix: _delete_