server:
  port: 8099
datasource:
  url: jdbc:postgresql://localhost:5432/go-together
  username: postgres
  password: 13693509
  continueOnError: true
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka
kafka:
  notificationTopicId: notification-service
  server: localhost:9092
  groupId: content-service
  replyPostfix: _reply
  readReplyPrefix: read_
  createReplyPrefix: create_
  updateReplyPrefix: update_
  deleteReplyPrefix: delete_

photo:
  store:
    path: store/