server:
  port: 8081
datasource:
  url: jdbc:postgresql://localhost:5432/go-together
  username: postgres
  password: 13693509
  continueOnError: true
  ddl-auto: update
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka
kafka:
  groupId: event-service
  server: localhost:9092

connectTimeout: 160000000
readTimeout: 160000000

spring:
  zipkin:
    base-url: http://localhost:9411/