server:
  port: 8080
zuul:
  host:
    connect-timeout-millis: 5000
    socket-timeout-millis: 10000
  routes:
    apartment-service:
      url: http://localhost:8081
    content-service:
      url: http://localhost:8099
    location-service:
      url: http://localhost:8090
    auth-service:
      url: http://localhost:8088
    order-service:
      url: http://localhost:8066
    message-service:
      url: http://localhost:8064
    room-service:
      url: http://localhost:8068
    user-service:
      url: http://localhost:8085
  prefix: /services
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000