server:
  port: 8080
zuul:
  host:
    connect-timeout-millis: 5000
    socket-timeout-millis: 10000
  routes:
    event-service:
      url: http://localhost:8081
    content-service:
      url: http://localhost:8099
    route-info-service:
      url: http://localhost:8098
    location-service:
      url: http://localhost:8090
    auth-service:
      url: http://localhost:8088
    message-service:
      url: http://localhost:8064
    user-service:
      url: http://localhost:8085
    notification-service:
      url: http://localhost:8097
  prefix: /services
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000