server:
  port: 8090
data:
  solr:
    host: http://localhost:8983/solr/
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka
feign:
  client:
    config:
      feignName:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: full