server:
  port: 8090
data:
  postgres:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 13693509
    ddl-auto: create
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka
feign:
  client:
    config:
      feignName:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: full