server:
  port: 8064
datasource:
  url: jdbc:postgresql://localhost:5432/go-together
  username: postgres
  password: 13693509
  continueOnError: true
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka
kafka:
  groupId: message-service
  server: localhost:9092