server:
  port: 8097
datasource:
  url: jdbc:postgresql://localhost:5432/go-together
  username: postgres
  password: 13693509
  continueOnError: true
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka
spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers:
            - localhost:9092
      bindings:
        notificationMessageInput:
          destination: notifications
          group: notificationsSubscriberGroup
      default:
        contentType: application/json