export const EVENTS_FIND_EVENTS = 'EVENTS_FIND_EVENTS';
export const EVENTS_PARAMETERS = 'EVENTS_PARAMETERS';
export const EVENTS_LANGUAGES = 'EVENTS_LANGUAGES';
export const EVENTS_APARTMENT_TYPES = 'EVENTS_APARTMENT_TYPES';