/*
 * This file is generated by jOOQ.
 */
package org.go.together.model;

import lombok.Data;
import lombok.EqualsAndHashCode;

import javax.persistence.Entity;
import javax.persistence.Table;

@EqualsAndHashCode(callSuper = true)
@Entity
@Data
@Table(name = "interest", schema = "user_service")
public class Interest extends NamedIdentifiedEntity {
}
