/*
 * This file is generated by jOOQ.
 */
package org.go.together.model;


import lombok.Data;
import org.go.together.interfaces.IdentifiedEntity;

import javax.persistence.*;
import java.util.UUID;


@Entity
@Data
@Table(name = "language", schema = "public")
public class Language implements IdentifiedEntity {
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private UUID id;
    private String name;
    private String code;
}
